name: CI Build

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - README.md
      - README_TEMPLATE.md
      - CHANGELOG.md

  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Codecov upload
        run: bash <(curl -s https://codecov.io/bash)
